### ISSUE TITLE
Can't update maps

### ISSUE THREAD

**Issue by BG-Music** [DigiWorm0/LevelImposter-Editor#1]
If there is an way, i can't find it, when i open an existing map and edit it then save it, it publishes as an new map (Does not edit the existing one).

**Comment by DigiWorm0** [comment]
Publishing always creates a new map. If you are just testing your map, you can just save it to your among us's maps folder. Otherwise, publishing is only for _finished_ among us maps as seen in rule #4:

`4. Maps cannot be in a broken or unusable state at time of publish.`

**Comment by BG-Music** [comment]
I meant this like if you already created one and published it and you can't overwrite it.

**Comment by DigiWorm0** [comment]
This is correct behavior because publishing is only for finished among us maps.

**Comment by BG-Music** [comment]
Would be nice to have that feature aging tho.

**Comment by BG-Music** [comment]
Would be nice to have that feature aging tho.

**Comment by BG-Music** [comment]
Would be nice to have that feature aging tho.
