### ISSUE TITLE
Unable To see new fungle sprites At Editor (beta version)

### ISSUE THREAD

**Issue by JeanTheFungle** [DigiWorm0/LevelImposter-Editor#14]
**hello i try the new editor at branch dev when i run npm start everything work but when i wante add Fungle Vent on the map sprite of vent dosen't show just a yellow cercle**

if you see this answer me and thx

**Comment by JeanTheFungle** [comment]
And on the log i saw two errors : 
`ERROR in src/components/properties/editors/MinigameEditorPanel.tsx:8:10
TS2614: Module '"../../../types/li/MapAssetDB"' has no exported member 'MapAsset'. Did you mean to use 'import MapAsset from "../../../types/li/MapAssetDB"' instead?
     6 | import DevInfo from "../../utils/DevInfo";
     7 | import ImageUpload from "../util/ImageUpload";
  >  8 | import { MapAsset } from "../../../types/li/MapAssetDB";
       |          ^^^^^^^^
     9 |
    10 | interface MinigameEditorPanelProps {
    11 |     minigameType: string;

ERROR in src/components/properties/panels/MeetingPanel.tsx:48:25
TS2322: Type '(spriteURL: string) => void' is not assignable to type '(asset: MapAsset) => void'.
  Types of parameters 'spriteURL' and 'asset' are incompatible.
    Type 'MapAsset' is not assignable to type 'string'.
    46 |                         defaultSpriteURL={"/sprites/util-meetingbackground.png"}
    47 |                         spriteURL={selectedElem.properties.meetingBackground}
  > 48 |                         onUpload={onUploadSprite}
       |                         ^^^^^^^^
    49 |                         onReset={onResetSprite}
    50 |                     />
    51 |                 </div>`

**Comment by DigiWorm0** [comment]
Why do you think this version is not released yet?

Development/Beta branches will almost always have bugs since they are WIP code bases. This is a known risk for any user who manually compiles/runs very untested code. Most of these bugs will be resolved before the version is released. Please refrain from making GitHub issues based on dev branches in the future.
