### ISSUE TITLE
Request for review of translation update

### ISSUE THREAD

**Issue by TianMengLucky** [DigiWorm0/LevelImposter-Editor#17]
I've updated the Simplified Chinese translation in gitlocalize, if you have the time please consider checking him out and merging the

https://gitlocalize.com/repo/8670/zh-CN/review/72063

**Comment by DigiWorm0** [comment]
Thank you for your contribution! I merged https://github.com/DigiWorm0/LevelImposter-Editor/pull/18 into our development branch. You'll see your changes appear in the next editor update.
