### ISSUE TITLE
language

### ISSUE THREAD

**Issue by TianMengLucky** [DigiWorm0/LevelImposter-Editor#2]
Whether to consider support for other languages

**Comment by DigiWorm0** [comment]
Support for i18n is currently being worked on. The most recent commit was 5845436c8eb082f46addba631a0ceb18b91260e5

**Comment by DigiWorm0** [comment]
To those interested in contributing for Hacktoberfest, many pages are ready for multi-language support in the editor. However, most are not.

A hook called `useTranslation()` is provided to access the local user's i18n translation in the form of an [LITranslation](https://github.com/DigiWorm0/LevelImposter-Editor/blob/master/src/types/localization/LITranslation.ts). 
Our goal is to have translations via this hook to be available throughout the application.
Once this is done, we can accept [translations](https://github.com/DigiWorm0/LevelImposter-Editor/tree/master/src/types/localization) from other users.

Thank you!
