### ISSUE TITLE
Not an Issue, Request if you're interested

### ISSUE THREAD

**Issue by cade69** [DigiWorm0/LevelImposter-Editor#4]
Hey Digi, I'm working with content creator socksfor1 (https://www.youtube.com/c/Socksfor1) we are looking to get some custom mods commissioned.
I'm curious to know if you would have any interest in modding the new game "Among Us VR" we are looking to create some of socks previous popular among us mods within that game.
Ideas such as No kill cooldown, custom roles, and teleportation capabilities.

If you have any interest and would like more details please contact me on discord, I can promise your time and efforts will be well worth while.
cade#6969

**Comment by DigiWorm0** [comment]
I'm uninterested,
also I'd recommend contacting future people using contact info that is linked in the README.md and not GitHub Issues or Curseforge.
